services:
  - type: web
    name: publicplus-ai
    runtime: python
    rootDir: "Ai services"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
